export default {
  id: 1,
  name: "\u0410\u043d\u0433\u043b\u0438\u0439\u0441\u043a\u0438\u0439",
  original_name: "english",
  system_info_title: "System Information",
  reinstall_os_title: "Reinstall the OS",
  network_statistics_title: "Network statistics",
  status: "Status",
  os: "OS",
  ip: "IP",
  login: "Login",
  password: "Password",
  note: "Password will be unavailable soon",
  not_available: "Not available",
  on: "Enabled",
  off: "Disabled",
  on_control_panel: "Enable",
  off_control_panel: "Disable",
  reboot_control_panel: "Reboot",
  reinstall: "Reinstall the OS",
  confirm: "Confirm",
  cancel: "Cancel",
  start: "Type ",
  middle: "I agree",
  keyword: "Keyword",
  end: " to confirm reinstalling the OS.",
  warning: "After reinstalling the OS ALL data will be deleted FOREVER!",
  in: "Incoming",
  out: "Outgoing",
  bit: "Bit",
  kbit: "KBit",
  mbit: "MBit",
  gbit: "GBit",
  tbit: "TBit",
  second: "sec",
  next: "Forward",
  back: "Back",
  data: "Loading data",
  network_statistics: "Loading network statistics",
  on_loading: "Turning on OS",
  off_loading: "Turning off OS",
  reboot_loading: "Rebooting OS",
  reinstall_loading: "Reinstalling the OS",
  operation_not_found: "Operation not found",
  key_not_found: "Key not found",
  invalid_key: "Invalid key",
  server_not_assigned: "You have not been issued server",
  server_not_found: "Server not found",
  unknown: "Unknown error"
}