// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XlgamesBackend.PostgreSQL;

#nullable disable

namespace XlgamesBackend.Migrations
{
    [DbContext(typeof(PostgreSQLContext))]
    [Migration("20250110184102_AddProjectDataLinks")]
    partial class AddProjectDataLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("XlgamesBackend.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Lang")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WHMCSName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "WHMCSName", "OriginalName", "Locale")
                        .IsUnique();

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("XlgamesBackend.Models.ProjectData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AboutUsSrc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discord")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Facebook")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GameHosting")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OGRNIP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Snapchat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telegram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Twitter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProjectDatas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutUsSrc = "...",
                            Contacts = "...",
                            Discord = "...",
                            Email = "...",
                            Facebook = "...",
                            GameHosting = "...",
                            INN = "...",
                            Instagram = "...",
                            Logo = "...",
                            Name = "...",
                            OGRNIP = "...",
                            PersonalAccount = "...",
                            PhoneNumber = "...",
                            Snapchat = "...",
                            Telegram = "...",
                            Twitter = "...",
                            Vk = "...",
                            Whatsapp = "...",
                            Year = 2025
                        });
                });

            modelBuilder.Entity("XlgamesBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ABOTHET",
                            Password = "$2a$11$7kcwh6TIVymeKyxCW1Kgf.TeSRjAo1jVHR6vAeSCTIQlsej7phrz."
                        });
                });

            modelBuilder.Entity("XlgamesBackend.Models.Language", b =>
                {
                    b.OwnsOne("XlgamesBackend.Models.Translates.AboutUs", "AboutUs", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.Contacts", "Contacts", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("INN")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IP")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OGRNIP")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.CookiePolicy", "CookiePolicy", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsOne("XlgamesBackend.Models.Block", "CookiePolicyBanner", b2 =>
                                {
                                    b2.Property<int>("CookiePolicyLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CookiePolicyLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("CookiePolicyLanguageId");
                                });

                            b1.OwnsMany("XlgamesBackend.Models.Block", "CookiePolicyCollection", b2 =>
                                {
                                    b2.Property<int>("CookiePolicyLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("CookiePolicyLanguageId", "Id");

                                    b2.ToTable("Languages_CookiePolicyCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("CookiePolicyLanguageId");
                                });

                            b1.Navigation("CookiePolicyBanner")
                                .IsRequired();

                            b1.Navigation("CookiePolicyCollection");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.DataCenters", "DataCenters", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.PrimitiveCollection<string[]>("DataCenterPoints")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsMany("XlgamesBackend.Models.Block", "DataCenterCollection", b2 =>
                                {
                                    b2.Property<int>("DataCentersLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("DataCentersLanguageId", "Id");

                                    b2.ToTable("Languages_DataCenterCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("DataCentersLanguageId");
                                });

                            b1.Navigation("DataCenterCollection");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.GameServer", "GameServer", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.GameServers", "GameServers", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("All")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Popular")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Search")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.Home", "Home", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("DataCentersDescription")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsMany("XlgamesBackend.Models.Block", "DataCenters", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId", "Id");

                                    b2.ToTable("Languages_DataCenters");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.OwnsOne("XlgamesBackend.Models.Block", "ServersWithGPU", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.OwnsOne("XlgamesBackend.Models.Block", "ServersWithoutGPU", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.OwnsOne("XlgamesBackend.Models.Block", "VPN", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.OwnsOne("XlgamesBackend.Models.Block", "VPS", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.OwnsOne("XlgamesBackend.Models.Block", "WebHosting", b2 =>
                                {
                                    b2.Property<int>("HomeLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("HomeLanguageId");

                                    b2.ToTable("Languages");

                                    b2.WithOwner()
                                        .HasForeignKey("HomeLanguageId");
                                });

                            b1.Navigation("DataCenters");

                            b1.Navigation("ServersWithGPU")
                                .IsRequired();

                            b1.Navigation("ServersWithoutGPU")
                                .IsRequired();

                            b1.Navigation("VPN")
                                .IsRequired();

                            b1.Navigation("VPS")
                                .IsRequired();

                            b1.Navigation("WebHosting")
                                .IsRequired();
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.News", "News", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.PrivacyPolicy", "PrivacyPolicy", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsMany("XlgamesBackend.Models.Block", "PrivacyPolicyCollection", b2 =>
                                {
                                    b2.Property<int>("PrivacyPolicyLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("PrivacyPolicyLanguageId", "Id");

                                    b2.ToTable("Languages_PrivacyPolicyCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("PrivacyPolicyLanguageId");
                                });

                            b1.Navigation("PrivacyPolicyCollection");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.ServersWithGPU", "ServersWithGPU", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.ServersWithoutGPU", "ServersWithoutGPU", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.Shared", "Shared", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("AboutUs")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyCPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyCountry")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyGPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyQuestionsCenter")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyQuestionsEnd")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyQuestionsStart")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnyRegion")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnySuggestionsCenter")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnySuggestionsEnd")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("AnySuggestionsStart")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Contacts")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Control")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CookiePolicy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Cores")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CurrencySign")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("CurrencySignPosition")
                                .HasColumnType("boolean");

                            b1.Property<string>("DataCenters")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DedicatedServers")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Discord")
                                .HasColumnType("boolean");

                            b1.Property<string>("Disk")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("DiskType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Email")
                                .HasColumnType("boolean");

                            b1.Property<string>("Error")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Facebook")
                                .HasColumnType("boolean");

                            b1.Property<string>("GHz")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("GPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("GameHosting")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("GameServers")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("INN")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IP")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Instagram")
                                .HasColumnType("boolean");

                            b1.Property<string>("Month")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("More")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("News")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("OGRNIP")
                                .HasColumnType("boolean");

                            b1.Property<string>("Order")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PersonalAccount")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("PhoneNumber")
                                .HasColumnType("boolean");

                            b1.Property<string>("PriceFrom")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PricePerMonth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PrivacyPolicy")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RAM")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("RAMType")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ReadMore")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ServersWithGPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ServersWithoutGPU")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Slots")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Snapchat")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Telegram")
                                .HasColumnType("boolean");

                            b1.Property<string>("TermsService")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Twitter")
                                .HasColumnType("boolean");

                            b1.Property<string>("VPN")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VPS")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Vk")
                                .HasColumnType("boolean");

                            b1.Property<string>("WebHosting")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("Whatsapp")
                                .HasColumnType("boolean");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.TermsService", "TermsService", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsMany("XlgamesBackend.Models.Block", "TermsServiceCollection", b2 =>
                                {
                                    b2.Property<int>("TermsServiceLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("TermsServiceLanguageId", "Id");

                                    b2.ToTable("Languages_TermsServiceCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("TermsServiceLanguageId");
                                });

                            b1.Navigation("TermsServiceCollection");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.VPN", "VPN", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Tariffs")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");

                            b1.OwnsMany("XlgamesBackend.Models.Block", "VPNCollection", b2 =>
                                {
                                    b2.Property<int>("VPNLanguageId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("VPNLanguageId", "Id");

                                    b2.ToTable("Languages_VPNCollection");

                                    b2.WithOwner()
                                        .HasForeignKey("VPNLanguageId");
                                });

                            b1.Navigation("VPNCollection");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.VPS", "VPS", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.OwnsOne("XlgamesBackend.Models.Translates.WebHosting", "WebHosting", b1 =>
                        {
                            b1.Property<int>("LanguageId")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Head")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("LanguageId");

                            b1.ToTable("Languages");

                            b1.WithOwner()
                                .HasForeignKey("LanguageId");
                        });

                    b.Navigation("AboutUs")
                        .IsRequired();

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("CookiePolicy")
                        .IsRequired();

                    b.Navigation("DataCenters")
                        .IsRequired();

                    b.Navigation("GameServer")
                        .IsRequired();

                    b.Navigation("GameServers")
                        .IsRequired();

                    b.Navigation("Home")
                        .IsRequired();

                    b.Navigation("News")
                        .IsRequired();

                    b.Navigation("PrivacyPolicy")
                        .IsRequired();

                    b.Navigation("ServersWithGPU")
                        .IsRequired();

                    b.Navigation("ServersWithoutGPU")
                        .IsRequired();

                    b.Navigation("Shared")
                        .IsRequired();

                    b.Navigation("TermsService")
                        .IsRequired();

                    b.Navigation("VPN")
                        .IsRequired();

                    b.Navigation("VPS")
                        .IsRequired();

                    b.Navigation("WebHosting")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
